### ISSUE TITLE
Not working with new version of Vite, dependency issue

### ISSUE THREAD

**Issue by Learning-X** [ivesia/vite-plugin-rewrite-all#1]
npm install --save-dev vite-plugin-rewrite-all

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-enterprise-boilerplate@0.0.0
npm ERR! Found: vite@3.0.3
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.0.2" from vite-plugin-rewrite-all@0.1.2
npm ERR! node_modules/vite-plugin-rewrite-all
npm ERR!   dev vite-plugin-rewrite-all@"^0.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/learningx/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/learningx/.npm/_logs/2022-07-28T13_19_47_167Z-debug-0.log

**Comment by Learning-X** [comment]
Is there anyone who can reply please?

**Comment by maietta** [comment]
Did you look at the contents of  /Users/learningx/.npm/_logs/2022-07-28T13_19_47_167Z-debug-0.log?

**Comment by Learning-X** [comment]
I understand this part, but this current plugin is not update to date with the new vite version.

**Comment by maietta** [comment]
Which version of Vue are you using? 2 or 3?

**Comment by Learning-X** [comment]
I'm using React - ^18.2.0

**Comment by alphatr** [comment]
I release a new version vite-plugin-rewrite-all@1.0.0 to support Vite 2 & 3, Please update it @Learning-X

**Comment by Learning-X** [comment]
Thank you very much, very appreciated @alphatr !!
