### ISSUE TITLE
Type error: Could not find a declaration file for module 'vite-plugin-rewrite-all'.

### ISSUE THREAD

**Issue by Shakeskeyboarde** [ivesia/vite-plugin-rewrite-all#3]
The package `exports` in are incorrect, which causes an error when resolving the types for this package.

As a workaround, you can re-declare the types in your project like you would for a package that had no types at all.

```ts
// Filename: src/vite-plugin-rewrite-all.d.ts

declare module 'vite-plugin-rewrite-all' {
  import { type ViteDevServer } from 'vite';

  declare function redirectAll(): {
    name: string;
    configureServer(server: ViteDevServer): () => void;
  };

  export { redirectAll as default };
}
```

See the related PR: #2

**Comment by alphatr** [comment]
#2 published a new version `vite-plugin-rewrite-all@1.0.2` to fixed.
