### ISSUE TITLE
Deprecate package?

### ISSUE THREAD

**Issue by silverwind** [ivesia/vite-plugin-rewrite-all#6]
With https://github.com/vitejs/vite/pull/14142 merged, I think this package serves no real purpose anymore since vite 5.0. Should it be deprecated?

**Comment by ilya-adnymics** [comment]
Can confirm - first I tried this plugin to fix the "[dot navigation](https://github.com/vitejs/vite/issues/2190)" issue (successfully). But after upgrading to Vite 5 and removing the plugin, the above mentioned issue is not present anymore.

**Comment by alphatr** [comment]
OK, I mark this package deprecated

**Comment by ilya-adnymics** [comment]
Props for the plugin though! Good job!
